create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 120),
  summary text not null default '' check (char_length(summary) <= 300),
  content text not null check (char_length(content) between 1 and 10000),
  author text not null default '관리자' check (char_length(author) between 1 and 30),
  published_at date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.notices enable row level security;

drop policy if exists "Public can view notices" on public.notices;
create policy "Public can view notices"
on public.notices
for select
to anon, authenticated
using (true);

create index if not exists notices_published_at_idx
on public.notices (published_at desc, id desc);

insert into public.notices
  (id,title,summary,content,author,published_at)
values
  (1,'서비스 이용 전 확인사항','예약 및 진행 일정은 고객센터 상담을 통해 조율해드립니다.','서비스 신청 전 아래 내용을 꼭 확인해 주세요.

[계정 정보 확인]
서비스 이용 전 본인의 계정 정보와 신청 내용을 정확하게 확인해 주세요.

[진행 일정 안내]
진행 일정은 상담 후 고객님의 일정에 맞춰 조율해드립니다.','관리자','2026-09-28'),
  (2,'아시아 서버 추가 비용 없이 이용 가능','아시아 서버 이용 시 별도의 추가 비용 없이 이용하실 수 있습니다.','아시아 서버 이용 시 별도의 추가 비용 없이 서비스를 이용하실 수 있습니다.

[서버 안내]
아시아 서버를 이용하시는 고객님도 별도 추가 비용 없이 신청하실 수 있습니다.

[상담 안내]
신청 전 고객센터를 통해 서버와 진행 일정을 확인해 주세요.','관리자','2026-09-29'),
  (3,'LOVE TEAM 사이트 오픈 안내','새로운 서비스와 이용 안내를 확인해주세요.','안녕하세요. LOVE TEAM 홈페이지가 새롭게 오픈되었습니다.

[홈페이지 안내]
가격표, 작업 내역, 후기, 자주 묻는 질문 등 주요 정보를 한 곳에서 편리하게 확인하실 수 있습니다.

[서비스 이용 안내]
원하시는 서비스를 확인하신 뒤 고객센터를 통해 상담을 진행해 주세요.','관리자','2026-10-01')
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.notices','id'),
  greatest(coalesce((select max(id) from public.notices),0),1),
  true
);